### ISSUE TITLE
cant access inventory after 64 bit update

### ISSUE THREAD

**Issue by tomas231** [Hypnootize/sunsethud#16] opened 2024-04-20 03:14 UTC
you can click the inventory button but once your there nothing shows up.

**Comment by Hypnootize** [comment] 2024-04-20 10:36
This has already been fixed in yesterday's update, did you already update the HUD and the problem is present?

**Comment by tomas231** [comment] 2024-04-20 16:43
yeah its working. didnt realize the hud got updated. sorry about that

**Comment by Hypnootize** [comment] 2024-04-20 17:09
No worries!

**Closed by Hypnootize** 2024-04-20 17:09 UTC
